# Generated by Django 4.2.7 on 2024-01-28 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_remove_product_added_at_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcart',
            name='added_at',
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
