# Generated by Django 4.2.7 on 2024-01-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0005_alter_product_description_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
